import "./Chat/Commands/cancel.js"
import "./Chat/Commands/copy.js"
import "./Chat/Commands/fill.js"
import "./Chat/Commands/help.js"
import "./Chat/Commands/paste.js"
import "./Chat/Commands/prefix.js"
import "./Chat/Commands/sphere.js"

import "./World Edit/CoordinateSystem.js"
import "./World Edit/PlaceBlock.js"